FROM amazoncorretto:21 AS builder

WORKDIR /build

RUN yum install -y unzip

{% if context in ['admincommon'] %}
    COPY ["BannerAdmin.war", "."]
    COPY ["BannerAdmin.ws.war", "."]
    RUN unzip BannerAdmin.war -d BannerAdmin && \
        rm BannerAdmin.war && \
        unzip BannerAdmin.ws.war -d BannerAdmin.ws && \
        rm BannerAdmin.ws.war

    WORKDIR /build/BannerAdmin.ws/WEB-INF/classes/
    COPY ["footer*.properties", "/tmp/"]
    RUN cat /tmp/footer*.properties >> config.properties && \
        sed -i "s/<session-timeout>60<\/session-timeout>/<session-timeout>\${banner9.session_timeout}<\/session-timeout>/" ../web.xml
    RUN sed -i '/<bean id="ticketValidator" class="org.jasig.cas.client.validation.Cas20ServiceTicketValidator">/,/^<\/bean>/s/Cas20ServiceTicketValidator/Saml11TicketValidator/;s/^<\/bean>$/<property name="tolerance" value="1000" \/>\n<\/bean>/g' ../applicationContext.xml

{% elif context in ['accessmgmt'] %}
    COPY ["BannerAccessMgmt.war", "."]
    COPY ["BannerAccessMgmt.ws.war", "."]
    RUN unzip BannerAccessMgmt.war -d BannerAccessMgmt && \
        rm BannerAccessMgmt.war && \
        unzip BannerAccessMgmt.ws.war -d BannerAccessMgmt.ws && \
        rm BannerAccessMgmt.ws.war

    WORKDIR /build/BannerAccessMgmt.ws/WEB-INF/classes/
    COPY ["footer*.properties", "/tmp/"]
    RUN cat /tmp/footer*.properties >> config.properties


{% elif context in ['ema'] %}
    COPY ["EllucianMessagingAdapter.zip", "."]
    RUN unzip EllucianMessagingAdapter.zip && \
        rm EllucianMessagingAdapter.zip && \
        mv EllucianMessagingAdapter*/*.war EllucianMessagingAdapter.war && \
        rm -fr `find * -type d` && \
        unzip EllucianMessagingAdapter.war -d EllucianMessagingAdapter && \
        rm EllucianMessagingAdapter.war

    WORKDIR /build/EllucianMessagingAdapter/WEB-INF/


{% elif context in ['bpapi'] %}
    COPY ["{{ app_name }}.war", "."]
    RUN unzip {{ app_name }}.war -d {{ app_name }} && \
        rm {{ app_name }}.war

    WORKDIR /build/BannerAdminBPAPI/WEB-INF/classes/
    COPY ["footer*.properties", "/tmp/"]
    RUN cat /tmp/footer*.properties >> config.properties && \
        sed -i "s/<session-timeout>60<\/session-timeout>/<session-timeout>\${banner9.session_timeout}<\/session-timeout>/" ../web.xml
    RUN sed -i '/<bean id="ticketValidator" class="org.jasig.cas.client.validation.Cas20ServiceTicketValidator">/,/^<\/bean>/s/Cas20ServiceTicketValidator/Saml11TicketValidator/;s/^<\/bean>$/<property name="tolerance" value="1000" \/>\n<\/bean>/g' ../applicationContext.xml


{% else %}
    COPY ["{{ app_name }}.war", "."]
    RUN unzip {{ app_name }}.war -d {{ app_name }} && \
        rm {{ app_name }}.war

    WORKDIR /build/{{ app_name }}/WEB-INF/classes/
    COPY ["footer*.groovy", "/tmp/"]
    RUN sed -i "s,\^APP_NAME\^,{{ app_name }}," /tmp/footer.groovy

    {% if context in ['accessmgmt'] %}
        RUN sed -i "s/<session-timeout>60<\/session-timeout>/<session-timeout>\${banner9.session_timeout}<\/session-timeout>/" ../web.xml
    {% endif %}

    {% if context.endswith('api') %}
        # echo a newline to the .groovy file before the adding the footer
        # (the file may not end with a newline)
        RUN echo >> {{ app_name }}_configuration.groovy && \
            cat /tmp/footer_api.groovy >> {{ app_name }}_configuration.groovy
    {% else %}
        # echo a newline to the .groovy file before the adding the footer
        # (the file may not end with a newline)
        RUN echo >> {{ app_name }}_configuration.groovy && \
            cat /tmp/footer*.groovy >> {{ app_name }}_configuration.groovy
    {% endif %}

    COPY ["banner_configuration.groovy", "/tmp/"]
    RUN cat /tmp/banner_configuration.groovy >> banner_configuration.groovy

{% endif %}


{% if context in ['accessmgmt', 'admincommon', 'bpapi',] %}
FROM tomcat:10.1-jre21
{% else %}
FROM tomcat:9-jre21
{% endif %}

ENV TZ={{ timezone }}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ["ojdbc8.jar", "/usr/local/tomcat/lib/"]

{% if context == 'bep' %}
    COPY ["bep_context.xml", "/usr/local/tomcat/conf/context.xml"]
    COPY ["bep_server.xml", "/usr/local/tomcat/conf/server.xml"]
{% else %}
    COPY ["context.xml", "/usr/local/tomcat/conf/"]
    COPY ["server.xml", "/usr/local/tomcat/conf/"]
{% endif %}

WORKDIR /usr/local/tomcat/webapps
COPY --from=builder /build/ ./

{% if context == 'appnav' %}
    COPY ["*.jpg", "{{ app_name }}/assets/backgrounds/"]
{% endif %}

WORKDIR /usr/local/tomcat/
COPY ["setenv.sh", "bin/setenv.sh"]

RUN useradd tomcat -u {{ hubado_host_uid }} && \
    mkdir /usr/local/tomcat/build && \
    chown -R tomcat.tomcat /usr/local/tomcat/build && \
    chown -R tomcat.tomcat /usr/local/tomcat/logs && \
    chown -R tomcat.tomcat /usr/local/tomcat/temp && \
    chown -R tomcat.tomcat /usr/local/tomcat/work && \
    # setenv.sh, which runs as tomcat at startup, modifies this file
    chown tomcat.tomcat /usr/local/tomcat/conf/catalina.properties

{% if context == 'ema' %}
RUN chown tomcat.tomcat /usr/local/tomcat/webapps/EllucianMessagingAdapter/WEB-INF/emsConfig.xml
{% endif %}

# For some reason, this jar causes an issue for these two
# This is likely a band-aid fix that won't be needed in the future
{% if context in ['bcm', 'studentapi',] %}
RUN rm /usr/local/tomcat/webapps/{{ app_name }}/WEB-INF/lib/slf4j-reload4j-1.7.36.jar
{% endif %}

USER tomcat

ENV CATALINA_OPTS="-DBANNER_APP_CONFIG=/usr/local/tomcat/webapps/{{ app_name }}/WEB-INF/classes/banner_configuration.groovy"

ENV CATALINA_OPTS="$CATALINA_OPTS -Doracle.jdbc.autoCommitSpecCompliant=false"

{% if context in ['appnav',] %}
    COPY ["limits.conf", "/etc/security/limits.conf"]
    ENV CATALINA_OPTS="$CATALINA_OPTS -server -Xms8g -Xmx8g"
{% elif context in ['admincommon',] %}
    ENV CATALINA_OPTS="$CATALINA_OPTS -server -Xms20g -Xmx20g"
{% else %}
    ENV CATALINA_OPTS="$CATALINA_OPTS -server -Xmx4g"
{% endif %}
