services:
    # External endpoint
    haproxy:
        build:
            context: contexts/haproxy
        ports:
            - "80:8080"
            - "443:8443"
        volumes:
            - ./volumes/ssl:/usr/local/etc/haproxy/ssl
        profiles: ["endpoints"]


    # Core application services
    accessmgmt:
        build:
            context: contexts/accessmgmt
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["core"]

    admincommon:
        build:
            context: contexts/admincommon
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["core"]

    appnav:
        build:
            context: contexts/appnav
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["core"]

    bcm:
        build:
            context: contexts/bcm
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["core"]

    extz:
        build:
            context: contexts/extz
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["core"]


    # API services
    bep:
        build:
            context: contexts/bep
        depends_on:
          - bep_rabbitmq
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["apis"]
    bep_rabbitmq:
        image: rabbitmq
        hostname: bep_rabbitmq
        env_file: conf/bep_rabbitmq.env
        volumes:
          - ./volumes/bep_rabbitmq:/var/lib/rabbitmq
        profiles: ["apis"]

    eeamc:
        build:
            context: contexts/eeamc
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["apis"]

    integrationapi:
        build:
            context: contexts/integrationapi
        volumes:
          - ./volumes/tomcat-env:/tomcat-env
        profiles: ["apis"]


    # Jenkins
    jenkins:
        build:
            context: contexts/jenkins
        volumes:
          - /mnt/deploy:/deploy
          - ./volumes/jenkins/start.sh:/opt/jenkins/start.sh:ro
          - ./volumes/jenkins/wgetrc:/home/jenkins/.wgetrc:ro
          - ./volumes/jenkins/war:/war
        profiles: ["jenkins"]

    # Monitoring
   # prometheus:
   #     image: prom/prometheus
   #     ports:
   #       - "9090:9090"
   #     volumes:
   #       - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
   #       - /prometheus

   # cadvisor:
   #     image: gcr.io/cadvisor/cadvisor:latest
   #     volumes:
   #         - /:/rootfs:ro
   #         - /var/run:/var/run:rw
   #         - /sys:/sys:ro
   #         - /var/lib/docker/:/var/lib/docker:ro

   # grafana:
   #     image: grafana/grafana
   #     volumes:
   #       - /etc/grafana/
   #       - /var/lib/grafana
