FROM openjdk:8 as builder

WORKDIR /build
COPY ["*.trz", "artifact.tar.gz"]
RUN tar -xzf artifact.tar.gz && \
    unzip */java/*.zip -d release

WORKDIR /build/release/installer
RUN chmod +x ant && \
    ./ant && \
    echo resource.SharedConfigurationHome.default=/build/shared > installer-store.properties && \
    echo resource.ModuleHome.default=/build/app >> installer-store.properties && \
    bin/install home

WORKDIR /build/app/current/instance/config
RUN sed -i "s/^ *authenticationProvider.*=.*/authenticationProvider='cas'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *active.*=.*/active=true/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *serverUrlPrefix.*=.*/serverUrlPrefix='\${cas.url}'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *serviceUrl.*=.*/serviceUrl='\${banner9.root}\/BannerExtensibility\/login\/cas'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *serverName.*=.*/serverName='\${banner9.root}'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *proxyCallbackUrl.*=.*/proxyCallbackUrl='\${banner9.root}\/BannerExtensibility\/secure\/receptor'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *afterLogoutUrl.*=.*/afterLogoutUrl='\${cas.url}\/logout\?url=\${banner9.root}\/BannerExtensibility\/'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *grails\.plugin\.springsecurity\.homePageUrl.*=.*/grails\.plugin\.springsecurity\.homePageUrl='\${banner9.root}\/BannerExtensibility'/" BannerExtensibility_configuration.groovy && \
    sed -i "s/^ *targetServer.*=.*/targetServer=\"tomcat\"/" BannerExtensibility_configuration.groovy

WORKDIR /build/app/current/installer
RUN chmod +x ant && \
    ./ant && \
    bin/systool war


FROM tomcat:8.5-jre8-openjdk

ENV TZ=^TIMEZONE^
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ["ojdbc8.jar", "/usr/local/tomcat/lib/"]
COPY ["xdb6.jar", "/usr/local/tomcat/lib/"]
COPY ["context.xml", "/usr/local/tomcat/conf/"]
COPY ["server.xml", "/usr/local/tomcat/conf/"]
COPY ["setenv.sh", "/usr/local/tomcat/bin/setenv.sh"]

WORKDIR /usr/local/tomcat/webapps
COPY --from=builder /build/app/current/dist/BannerExtensibility-*.war BannerExtensibility.war
RUN unzip BannerExtensibility.war -d BannerExtensibility && \
    rm BannerExtensibility.war

WORKDIR /usr/local/tomcat/
RUN useradd tomcat && \
    chown -R tomcat.tomcat /usr/local/tomcat
USER tomcat

# Temporary patch for CVE-2022-35912, see https://grails.org/blog/2022-07-18-rce-vulnerability.html
RUN mkdir /tmp/grails
WORKDIR /tmp/grails
RUN wget https://github.com/grails/grails-core/releases/download/v3.3.15/grails-3.3.15.zip
RUN unzip grails-3.3.15.zip
WORKDIR /usr/local/tomcat/webapps/BannerExtensibility/WEB-INF/lib
RUN ls grails*3.3.11.jar | sed s/3\\.3\\.11/3.3.15/g | xargs -iFILE mv /tmp/grails/grails-3.3.15/dist/FILE .
RUN rm grails*-3.3.11.jar
RUN rm -fr /tmp/grails
WORKDIR /usr/local/tomcat/
