FROM amazoncorretto:11

WORKDIR /opt/jenkins

RUN yum install -y shadow-utils wget

RUN useradd -mr jenkins -u ^HUBADO_HOST_UID^
RUN chown -R jenkins /opt/jenkins
USER jenkins

CMD ["bash", "start.sh"]
