FROM openjdk:8 as builder

WORKDIR /build
COPY ["*.trz", "artifact.tar.gz"]
RUN tar -xzf artifact.tar.gz && \
    unzip */java/*.zip -d release

WORKDIR /build/release/installer
RUN chmod +x ant && \
    ./ant && \
    echo resource.SharedConfigurationHome.default=/build/shared > installer-store.properties && \
    echo resource.ModuleHome.default=/build/app >> installer-store.properties && \
    bin/install home

WORKDIR /build/app/current/instance/config
RUN sed -i "s/^\s*host = \"rabbitmqHost\"/host=\"bep_rabbitmq\"/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*port = \"rabbitmqPort\"/port=\"5672\"/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*userName = \"rabbitmqAdm\"/userName=\"\${bep_rabbitmq.user}\"/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*password = \"#UPDATEME#\"/password=\"\${bep_rabbitmq.password}\"/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*authenticationProvider.*=.*/authenticationProvider='cas'/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*active.*=.*/active=true/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*serviceUrl.*=.*/serviceUrl='\${banner9.root}\/BannerEventPublisher\/login\/cas'/" BannerEventPublisher_configuration.groovy && \ 
    sed -i "s/^\s*serverName.*=.*/serverName='\${banner9.root}'/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*proxyCallbackUrl.*=.*/proxyCallbackUrl='\${banner9.root}\/BannerEventPublisher\/secure\/receptor'/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*afterLogoutUrl.*=.*/afterLogoutUrl='\${cas.url}\/logout\?url=\${banner9.root}\/BannerEventPublisher\/'/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*grails\.plugin\.springsecurity\.homePageUrl.*=.*/grails\.plugin\.springsecurity\.homePageUrl='\${banner9.root}\/'/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^\s*targetServer.*=.*/targetServer=\"tomcat\"/" BannerEventPublisher_configuration.groovy && \
    sed -i "s/^grails.plugin.springsecurity.cas.serverUrlPrefix.*/grails.plugin.springsecurity.cas.serverUrlPrefix='\${cas.url}'/" BannerEventPublisher_configuration.groovy

WORKDIR /build/app/current/installer
RUN chmod +x ant && \
    ./ant && \
    bin/systool war


FROM tomcat:8.5-jre8-openjdk

ENV TZ=^TIMEZONE^
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ["ojdbc8.jar", "/usr/local/tomcat/lib/"]
COPY ["bep_context.xml", "/usr/local/tomcat/conf/context.xml"]
COPY ["bep_server.xml", "/usr/local/tomcat/conf/server.xml"]
COPY ["setenv.sh", "/usr/local/tomcat/bin/setenv.sh"]

WORKDIR /usr/local/tomcat/webapps
COPY --from=builder /build/app/current/dist/BannerEventPublisher-*.war BannerEventPublisher.war
RUN unzip BannerEventPublisher.war -d BannerEventPublisher && \
    rm BannerEventPublisher.war

WORKDIR /usr/local/tomcat/
RUN useradd tomcat && \
    chown -R tomcat.tomcat /usr/local/tomcat
USER tomcat

# Temporary patch for CVE-2022-35912, see https://grails.org/blog/2022-07-18-rce-vulnerability.html
RUN mkdir /tmp/grails
WORKDIR /tmp/grails
RUN wget https://github.com/grails/grails-core/releases/download/v3.3.15/grails-3.3.15.zip
RUN unzip grails-3.3.15.zip
WORKDIR /usr/local/tomcat/webapps/BannerEventPublisher/WEB-INF/lib
RUN ls grails*3.3.11.jar | sed s/3\\.3\\.11/3.3.15/g | xargs -iFILE mv /tmp/grails/grails-3.3.15/dist/FILE .
RUN rm grails*-3.3.11.jar
RUN rm -fr /tmp/grails
WORKDIR /usr/local/tomcat/
